### ISSUE TITLE
ML-Präsentation

### ISSUE THREAD

**Issue by Ermodo** [DHBWMannheim/MachineLearning#2]

**Comment by Ermodo** [comment]
@troykessler Kannst du hier schonmal die mögliche Aufteilungsthemen hinzufügen?

**Comment by troykessler** [comment]
Machine Learning Präsentations Aufteilung:

Teil 1 (Einführung Projekt, Sentiment Model, Daten laden, batches aufteilen) @Patrickmischka 
Teil 2 (Sentiment Model, normalisieren, vektorisieren, performance) @Ermodo 
Teil 3 (Sentiment Model, Modellaufbau, trainieren, testen, interpretation accuracy & loss) @troykessler 
Teil 4 (Technical Model, Daten laden, Indikatoren bis Modeldefinition) @jangruebener 
Teil 5 (Technical Model, Modellaufbau, trainieren, testen, interpretation loss) @Michi0400 
Teil 6 (Vorstellung der live ergebnisse von sentiment & technical modell) @aaronschweig 

Unterteilung wird im notebook mit namen markiert
