### ISSUE TITLE
Evaluate Ups and Downs of creating separate / dedicated Notebooks

### ISSUE THREAD

**Issue by michael-spengler** [DHBWMannheim/MachineLearning#4]
1. for Sentiment Analysis
2. for Technical Analysis Price Prediction

Background: Separation of Concerns 

Additionally:
You can separate the data preprocessing part from the Model Creation Part

**Comment by jangruebener** [comment]
Hi Michael, lass uns den Issue bitte in dem Repo für unsere [ML-Server](https://github.com/DHBWMannheim/ml-server) aufmachen und dort betrachten. Das in diesem Repo vorhandene Jupyter Notebook ist unsere Prüfungsleistung für die Vorlesung neue Konzepte II und zielt dabei in erster Linie auf die verwendeten Modelle und die Datenaufbereitung ab. Da das Notebook nicht für den Produktionsbetrieb gedacht ist, geht es hier mehr um die Dokumentation der Ergebnisse als Prüfungsleistung und um die relevanten Infos zum Vorgehen etc. an einem Ort zu haben. In dem anderen Repo können wir gerne mal einen Blick drauf werfen, wo wir auf Code Ebene des Servers noch etwas an der Performance rauskitzeln können und wo wir zum Beispiel die Separation of Concerns verbessern können.

**Comment by michael-spengler** [comment]
Potential role model for better separation of concerns: https://github.com/divyanshbajpai/EVA4-Coursework/tree/master/Assignment-12/Part-A
