### ISSUE TITLE
Executability could be improved easily - challenges see below

### ISSUE THREAD

**Issue by michael-spengler** [DHBWMannheim/MachineLearning#5]
![Screenshot 2021-04-19 at 17 10 56](https://user-images.githubusercontent.com/43786652/115259800-7ea34c80-a132-11eb-9fc4-888c1013f0fd.png)

**Comment by Ermodo** [comment]
@michael-spengler Hey, wir wissen, das das etwas unerwartet ist. Wir haben das Problem, dass wir nicht einfach einen so großen Datensatz in GitHub ablegen können. Deswegen ist der Datensatz verlinked und in der Readme / im Notebook bei Setup verwiesen "Das Datenset für das Trainieren kann über [diesen Link](https://www.dropbox.com/s/ur7pw797mgcc1wr/tweets.csv?dl=0) heruntergeladen werden. Dabei muss die Datei "tweets.csv" in den gleichen Ordner wie dieses Notepad abgelegt werden."
